# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.2
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
       
    steps:
      - run:
          name: "Checking Versions"
          command: |
            sudo npm i npm@latest -g
            node --version
            npm --version
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # greenkeeper-lockfile update
      - run: sudo npm install greenkeeper-lockfile@1 -g
      # install deps - without sudo
      - run: npm install --unsafe-perm=true --allow-root
      - run: greenkeeper-lockfile-update
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests
      - run: npm test
      # push lockfile to repo
      - run: greenkeeper-lockfile-upload
      
      # Store results
      - store_test_results:
          path: test-results/jest
      - store_artifacts:
          path: /tmp/artifacts